# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProtobufDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ProtobufDemo

pod 'Protobuf', '~> 3.4.0'
  target 'ProtobufDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProtobufDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
